config/routes.rb
Rails.application.routes.draw do
  root 'top#main'
  get 'top/main'
  resources :products
  resources :cart_items, only: [:create, :destroy]
  resources :carts, only: [:show]
  # get 'top/main'
  # get 'products/index'
  # get 'products/new'
  # get 'carts/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    #has_one :cart_item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_cart
            if session[:cart_id]
                cart = Cart.find(session[:cart_id])
            else
                cart = Cart.create
                session[:cart_id] = cart.id
            end
            cart
        end
        helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    
    def create 
        @cart_item = current_cart.cart_items.find_by(product_id: params[:cart_item][:product_id])
        if @cart_item.blank?
            @cart_item = current_cart.cart_items.build(product_id: params[:cart_item][:product_id], qty: 0)
        end
        @cart_item.qty += params[:cart_item][:qty].to_i
        if @cart_item.save
        end
        redirect_to current_cart
    end
    
    def destroy
        @cart_item = current_cart.cart_items.find_by(product_id: params[:product_id])
        @cart_item.destroy
        redirect_to current_cart
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart_items = current_cart.cart_items
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(name: params[:name], price: params[:price])
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end
  
  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
      @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<h1>カート</h1>

<% @cart_items.each do |c| %>
<p>
  名前 : <%= c.product.name %><br>
  価格 : <%= c.product.price %>円<br>
  個数 : <%= c.qty %>個<br>
  合計金額 : <%= c.product.price * c.qty %>円<br>
  <%= link_to '削除', cart_item_path(product_id: c.product.id), method: :delete %><br>
  -------------------------------------------
</p>
<% end %>

<%= link_to 'to main', top_main_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>商品管理</h1>
<% @products.each do |p| %>
<p>
  商品名 : <%= p.name %><br>
  価格 : <%= p.price %>円<br>
  <%= link_to '削除', product_path(p.id), method: :delete %><br>
  -------------------------------------------
</p>
<% end %>

<%= link_to '商品を登録する', new_product_path %>

<%= link_to 'to main', top_main_path %>

app/views/products/new.html.erb
<h1>商品登録</h1>

<%= form_tag action: :create do %>
<p><%= label_tag :name, '商品名 : ' %>
<%= text_field_tag :name %></p>
<p><%= label_tag :price, '価格 : ' %>
<%= text_field_tag :price %>円</p>
<%= submit_tag '登録' %>
<% end %>

<p>
    <%= link_to '戻る', :back %>
</p>

app/views/top/main.html.erb
<h1>商品一覧</h1>
<% @products.each do |p| %>
<p>
    商品名 : <%= p.name %><br>
    価格 : <%= p.price %><br>
  <% @cart_item = current_cart.cart_items.build %>
  <%= form_for @cart_item, url: cart_items_path do |f| %>
   <%= f.label :qty, "数量"%>
   <%= f.number_field :qty %>
   <%= f.hidden_field :product_id, :value => p.id %>
   <%= f.submit '確定' %>
  <% end %>
</p>
  -------------------------------------------

<% end %>

<%= link_to '商品一覧', products_path %>
<%= link_to 'カート', cart_path(current_cart) %>